# The settings from this file can be overriden from a local `docker-compose.override.yml`-file.
# See: https://docs.docker.com/compose/multiple-compose-files/

# You only need to set the values you want to override.
# For example:
# -------------------------------------------
# services:
#   121-service:
#     command: 'npm run start:app-map'
# -------------------------------------------
# Save the above snippet as `docker-compose.override.yml` in the same directory as this file.
# And run the `npm run start:services:override`-command.

services:
  121-service:
    build:
      target: development
    ports:
      - '${PORT_121_SERVICE}:${PORT_121_SERVICE}'
      - '9229:9229' # Node.js remote-debugging
    volumes:
      - '121_service_node_modules:/home/node/app/node_modules'
      - './121-service:/home/node/app'
    # For debugging:
    #
    # Start with an interactive shell:
    # command: "sh"
    #
    # Install new (dev-)dependencies:
    # command: 'npm install --no-fund'
    #
    # Run in production-mode (also set `targert: production` in the build-section):
    # command: 'npm start'
    #
    # Run in AppMap-mode (See README.md#):
    # command: 'npm run start:app-map'
    #
    # Run in local-development watch-mode:
    command: 'npm run start:dev'

  mock-service:
    build:
      target: development
    volumes:
      - 'mock_service_node_modules:/home/node/app/node_modules'
      - './mock-service:/home/node/app'

volumes:
  121_service_node_modules:
  mock_service_node_modules:
